package ke.skyworld.mbanking.ussdapplication;

public class AppConstants {

    public final static String strHomeMenuHeader = "Welcome to APSTAR Mobile Banking";
    public final static String strMobileBankingName = "APSTAR Mobile Banking";
    public final static String strSACCOName = "Apstar SACCO";
    public final static String strAppID = "Apstar SACCO";
    public final static String strSettingParamName = "ORGANIZATION_MBANKING_SETTINGS";
    public final static String strServiceUnavailable = "Sorry, you are currently unable to access this service. Please visit one of our branches or contact us on +254111035600.\n\nERR_MBM100\n";
    public final static String strSACCOProductName = "APSTAR";
    public final static String strSACCOUSSDCode = "*882#";
    public final static String strSACCOUSSDSubCode = "*9#";

    public enum SPProviderCode {
        SAFARICOM(101),
        AIRTEL(102),
        Cooperative_Bank(201),
        KCB(202),
        Equity_Bank(203),
        Standard_Chartered_Bank(204),
        Barclays_Bank(205);
        //Postbank(206);
        private final int intValue;

        SPProviderCode(int theValue) {
            this.intValue = theValue;
        }

        public int getValue() {
            return intValue;
        }
    }

    public enum SPProviderAccountCode {
        //SAFARICOM
        SAFARICOM_B2C("10101"),
        SAFARICOM_C2B("10102"),
        SAFARICOM_B2B("10103"),
        KPLC_TOKEN("10104"),
        KPLC_Postpaid("10105"),
        Nairobi_Water("10106"),
        DStv("10107"),
        ZUKU("10108"),
        GOtv("10109"),
        StarTimes("10110");

        private final String strValue;

        SPProviderAccountCode(String theValue) {
            this.strValue = theValue;
        }

        public String getValue() {
            return strValue;
        }
    }

    public enum USSDDiplayText {
        EXIT("Thank you for using our services.");

        private final String strValue;

        USSDDiplayText(String theValue) {
            this.strValue = theValue;
        }

        public String getValue() {
            return strValue;
        }
    }

    public enum USSDProvider {
        SAFARICOM(101),
        AIRTEL(102),
        TELKOM(103),
        YU(104),
        EQUITEL(105),
        INTERNATIONAL_GATEWAY(201);

        private final int intValue;

        USSDProvider(int theValue) {
            this.intValue = theValue;
        }

        public int getValue() {
            return intValue;
        }
    }

    public enum USSDDataType {
        INIT("INIT(INIT)"),
        // -- For Future reference if OUT_MAIN_MENU Menus is required
        //OUT_MAIN_MENU
        MAIN_OUT_MENU(USSDDataType.INIT.getValue() + "-MAIN_OUT(MENU)"),
        //LOGIN_PIN(USSDDataType.MAIN_OUT_MENU.getValue() + "-LOGIN(PIN)"), //MAIN_OUT_MENU NOT USED therefore Menu Starts at Login

        LOGIN_PIN(USSDDataType.INIT.getValue() + "-LOGIN(PIN)"),

        //MAIN_IN_MENU
        MAIN_IN_MENU(USSDDataType.LOGIN_PIN.getValue() + "-MAIN_IN(MENU)"),

        //DIVIDENDS_REQUEST
        DIVIDENDS_REQUEST_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-DIVIDENDS_REQUEST(MENU)"),
        DIVIDENDS_REQUEST_AMOUNT(USSDDataType.DIVIDENDS_REQUEST_MENU.getValue() + "-DIVIDENDS_REQUEST(AMOUNT)"),
        DIVIDENDS_REQUEST_PIN(USSDDataType.DIVIDENDS_REQUEST_AMOUNT.getValue() + "-DIVIDENDS_REQUEST(PIN)"),
        DIVIDENDS_REQUEST_CONFIRMATION(USSDDataType.DIVIDENDS_REQUEST_PIN.getValue() + "-DIVIDENDS_REQUEST(CONFIRMATION)"),
        DIVIDENDS_REQUEST_END(USSDDataType.DIVIDENDS_REQUEST_CONFIRMATION.getValue() + "-DIVIDENDS_REQUEST(END)"),



        //WITHDRAWAL
        WITHDRAWAL_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-WITHDRAWAL(MENU)"),
        WITHDRAWAL_OPTION(USSDDataType.WITHDRAWAL_MENU.getValue() + "-WITHDRAWAL(OPTION)"),
        WITHDRAWAL_TO_OPTION(USSDDataType.WITHDRAWAL_MENU.getValue() + "-WITHDRAWAL(TO_OPTION)"),
        WITHDRAWAL_TO(USSDDataType.WITHDRAWAL_OPTION.getValue() + "-WITHDRAWAL(TO)"),
        WITHDRAWAL_CUSTOMER(USSDDataType.WITHDRAWAL_TO.getValue() + "-WITHDRAWAL(CUSTOMER)"),
        WITHDRAWAL_ACCOUNT(USSDDataType.WITHDRAWAL_CUSTOMER.getValue() + "-WITHDRAWAL(ACCOUNT)"),
        WITHDRAWAL_ATM_OPTION(USSDDataType.WITHDRAWAL_CUSTOMER.getValue() + "-WITHDRAWAL(ATM_OPTION)"),
        WITHDRAWAL_AGENT_OPTION(USSDDataType.WITHDRAWAL_CUSTOMER.getValue() + "-WITHDRAWAL(AGENT_OPTION)"),
        WITHDRAWAL_AMOUNT(USSDDataType.WITHDRAWAL_ACCOUNT.getValue() + "-WITHDRAWAL(AMOUNT)"),
        WITHDRAWAL_PIN(USSDDataType.WITHDRAWAL_AMOUNT.getValue() + "-WITHDRAWAL(PIN)"),
        WITHDRAWAL_CONFIRMATION(USSDDataType.WITHDRAWAL_PIN.getValue() + "-WITHDRAWAL(CONFIRMATION)"),
        WITHDRAWAL_END(USSDDataType.WITHDRAWAL_CONFIRMATION.getValue() + "-WITHDRAWAL(END)"),

        //UTILITIES
        UTILITIES_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-UTILITIES(MENU)"),

        //ETOPUP(Airtime etc.)
        ETOPUP_MNO_OPTION(USSDDataType.UTILITIES_MENU.getValue() + "-ETOPUP(MNO_OPTION)"),
        ETOPUP_TO_OPTION(USSDDataType.ETOPUP_MNO_OPTION.getValue() + "-ETOPUP(TO_OPTION)"),
        ETOPUP_TO(USSDDataType.ETOPUP_TO_OPTION.getValue() + "-ETOPUP(TO)"),
        ETOPUP_CUSTOMER(USSDDataType.ETOPUP_TO.getValue() + "-ETOPUP(CUSTOMER)"),
        ETOPUP_ACCOUNT(USSDDataType.ETOPUP_CUSTOMER.getValue() + "-ETOPUP(ACCOUNT)"),
        ETOPUP_AMOUNT(USSDDataType.ETOPUP_ACCOUNT.getValue() + "-ETOPUP(AMOUNT)"),
        ETOPUP_PIN(USSDDataType.ETOPUP_AMOUNT.getValue() + "-ETOPUP(PIN)"),
        ETOPUP_CONFIRMATION(USSDDataType.ETOPUP_PIN.getValue() + "-ETOPUP(CONFIRMATION)"),
        ETOPUP_END(USSDDataType.ETOPUP_CONFIRMATION.getValue() + "-ETOPUP(END)"),

        //BILL (KPLC, NAIROBI WATER, DSTV etc.)
        PAY_BILL_BILLER_ACCOUNT(USSDDataType.UTILITIES_MENU.getValue() + "-PAY_BILL(BILLER_ACCOUNT)"),
        PAY_BILL_BILLER_CUSTOMER(USSDDataType.PAY_BILL_BILLER_ACCOUNT.getValue() + "-PAY_BILL(CUSTOMER)"),
        PAY_BILL_FROM_ACCOUNT(USSDDataType.PAY_BILL_BILLER_CUSTOMER.getValue() + "-PAY_BILL(FROM_ACCOUNT)"),
        PAY_BILL_AMOUNT(USSDDataType.PAY_BILL_FROM_ACCOUNT.getValue() + "-PAY_BILL(AMOUNT)"),
        PAY_BILL_PIN(USSDDataType.PAY_BILL_AMOUNT.getValue() + "-PAY_BILL(PIN)"),
        PAY_BILL_CONFIRMATION(USSDDataType.PAY_BILL_PIN.getValue() + "-PAY_BILL(CONFIRMATION)"),
        PAY_BILL_END(USSDDataType.PAY_BILL_CONFIRMATION.getValue() + "-PAY_BILL(END)"),



        //PAY_BILL_MAINTENANCE_ACCOUNT
        PAY_BILL_MAINTENANCE_ACCOUNT_MENU(USSDDataType.UTILITIES_MENU.getValue() + "-PAY_BILL_MAINTENANCE_ACCOUNT(MENU)"),
        PAY_BILL_MAINTENANCE_ACCOUNT_ACCOUNT(USSDDataType.PAY_BILL_MAINTENANCE_ACCOUNT_MENU.getValue() + "-PAY_BILL_MAINTENANCE_ACCOUNT(ACCOUNT)"),
        PAY_BILL_MAINTENANCE_ACCOUNT_NAME(USSDDataType.PAY_BILL_MAINTENANCE_ACCOUNT_ACCOUNT.getValue() + "-PAY_BILL_MAINTENANCE_ACCOUNT(NAME)"),
        PAY_BILL_MAINTENANCE_ACCOUNT_REMOVE(USSDDataType.PAY_BILL_MAINTENANCE_ACCOUNT_MENU.getValue() + "-PAY_BILL_MAINTENANCE_ACCOUNT(REMOVE)"),

        //FIXME: TEMPORARY
        MPESA_FLOAT_PURCHASE_CUSTOMER(USSDDataType.UTILITIES_MENU.getValue() + "-MPESA_FLOAT_PURCHASE(CUSTOMER)"),
        MPESA_FLOAT_PURCHASE_ACCOUNT(USSDDataType.PAY_BILL_BILLER_CUSTOMER.getValue() + "-MPESA_FLOAT_PURCHASE(ACCOUNT)"),
        MPESA_FLOAT_PURCHASE_AGENT_NO(USSDDataType.MPESA_FLOAT_PURCHASE_ACCOUNT.getValue() + "-MPESA_FLOAT_PURCHASE(AGENT_NO)"),
        MPESA_FLOAT_PURCHASE_AGENT_NAME(USSDDataType.MPESA_FLOAT_PURCHASE_AGENT_NO.getValue() + "-MPESA_FLOAT_PURCHASE(AGENT_NAME)"),
        MPESA_FLOAT_PURCHASE_STORE_NO(USSDDataType.MPESA_FLOAT_PURCHASE_AGENT_NAME.getValue() + "-MPESA_FLOAT_PURCHASE(STORE_NO)"),
        MPESA_FLOAT_PURCHASE_AMOUNT(USSDDataType.MPESA_FLOAT_PURCHASE_STORE_NO.getValue() + "-MPESA_FLOAT_PURCHASE(AMOUNT)"),
        MPESA_FLOAT_PURCHASE_PIN(USSDDataType.MPESA_FLOAT_PURCHASE_AMOUNT.getValue() + "-MPESA_FLOAT_PURCHASE(PIN)"),
        MPESA_FLOAT_PURCHASE_CONFIRMATION(USSDDataType.MPESA_FLOAT_PURCHASE_PIN.getValue() + "-MPESA_FLOAT_PURCHASE(CONFIRMATION)"),
        MPESA_FLOAT_PURCHASE_END(USSDDataType.MPESA_FLOAT_PURCHASE_CONFIRMATION.getValue() + "-MPESA_FLOAT_PURCHASE(END)"),
        //FIXME: END OF TEMPORARY

        //DEPOSIT
        DEPOSIT_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-DEPOSIT(MENU)"),
        DEPOSIT_CUSTOMER(USSDDataType.DEPOSIT_MENU.getValue() + "-DEPOSIT(CUSTOMER)"),
        DEPOSIT_ACCOUNT(USSDDataType.DEPOSIT_CUSTOMER.getValue() + "-DEPOSIT(ACCOUNT)"),
        DEPOSIT_SHARE(USSDDataType.DEPOSIT_MENU.getValue() + "-DEPOSIT(SHARE)"),
        DEPOSIT_AMOUNT(USSDDataType.DEPOSIT_ACCOUNT.getValue() + "-DEPOSIT(AMOUNT)"),
        DEPOSIT_PIN(USSDDataType.DEPOSIT_AMOUNT.getValue() + "-DEPOSIT(PIN)"),
        DEPOSIT_CONFIRMATION(USSDDataType.DEPOSIT_PIN.getValue() + "-DEPOSIT(CONFIRMATION)"),
        DEPOSIT_END(USSDDataType.DEPOSIT_CONFIRMATION.getValue() + "-DEPOSIT(END)"),

        /*
        //DEPOSIT
        DEPOSIT_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-DEPOSIT(MENU)"),
            DEPOSIT_ACCOUNT(USSDDataType.DEPOSIT_MENU.getValue() + "-DEPOSIT(ACCOUNT)"),
                DEPOSIT_AMOUNT(USSDDataType.DEPOSIT_ACCOUNT.getValue() + "-DEPOSIT(AMOUNT)"),
                    DEPOSIT_PIN(USSDDataType.DEPOSIT_AMOUNT.getValue() + "-DEPOSIT(PIN)"),
                        DEPOSIT_CONFIRMATION(USSDDataType.DEPOSIT_PIN.getValue() + "-DEPOSIT(CONFIRMATION)"),
                            DEPOSIT_END(USSDDataType.DEPOSIT_CONFIRMATION.getValue() + "-DEPOSIT(END)"),
         */
        //MY ACCOUNT
        MY_ACCOUNT_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-MY_ACCOUNT(MENU)"),
        //GENERAL
						/*
						MY_ACCOUNT_ACCOUNT(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MY_ACCOUNT(ACCOUNT)"),
							MY_ACCOUNT_PIN(USSDDataType.MY_ACCOUNT_ACCOUNT.getValue() + "-MY_ACCOUNT(PIN)"),
								MY_ACCOUNT_END(USSDDataType.MY_ACCOUNT_PIN.getValue() + "-MY_ACCOUNT(END)"),
						*/

        //BALANCE
        MY_ACCOUNT_BALANCE_MENU(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MY_ACCOUNT_BALANCE(MENU)"),//For type: FOSA / BOSA / ALL
        MY_ACCOUNT_BALANCE_CUSTOMER(USSDDataType.MY_ACCOUNT_BALANCE_MENU.getValue() + "-MY_ACCOUNT_BALANCE(CUSTOMER)"),//For type: FOSA / BOSA / ALL
        MY_ACCOUNT_BALANCE_ACCOUNT(USSDDataType.MY_ACCOUNT_BALANCE_CUSTOMER.getValue() + "-MY_ACCOUNT_BALANCE(ACCOUNT)"),//For type: FOSA / BOSA / ALL
        MY_ACCOUNT_BALANCE_PIN(USSDDataType.MY_ACCOUNT_BALANCE_MENU.getValue() + "-MY_ACCOUNT_BALANCE(PIN)"),
        MY_ACCOUNT_BALANCE_END(USSDDataType.MY_ACCOUNT_BALANCE_PIN.getValue() + "-MY_ACCOUNT_BALANCE(END)"),


        //SAVINGS_ACCOUNT_ACTIVATION
        SAVINGS_ACCOUNT_ACTIVATION_PIN(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-SAVINGS_ACCOUNT_ACTIVATION(PIN)"),
        SAVINGS_ACCOUNT_ACTIVATION_CONFIRMATION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-SAVINGS_ACCOUNT_ACTIVATION(CONFIRMATION)"),
        SAVINGS_ACCOUNT_ACTIVATION_END(USSDDataType.SAVINGS_ACCOUNT_ACTIVATION_CONFIRMATION.getValue() + "-SAVINGS_ACCOUNT_ACTIVATION(END)"),

        //MINI STATEMENT
        MY_ACCOUNT_MINI_STATEMENT_MENU(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MY_ACCOUNT_MINI_STATEMENT(MENU)"),//For type: FOSA / BOSA / ALL
        MY_ACCOUNT_MINI_STATEMENT_CUSTOMER(USSDDataType.MY_ACCOUNT_MINI_STATEMENT_MENU.getValue() + "-MY_ACCOUNT_MINI_STATEMENT(CUSTOMER)"),
        MY_ACCOUNT_MINI_STATEMENT_ACCOUNT(USSDDataType.MY_ACCOUNT_MINI_STATEMENT_CUSTOMER.getValue() + "-MY_ACCOUNT_MINI_STATEMENT(ACCOUNT)"),
        MY_ACCOUNT_MINI_STATEMENT_PIN(USSDDataType.MY_ACCOUNT_MINI_STATEMENT_ACCOUNT.getValue() + "-MY_ACCOUNT_MINI_STATEMENT(PIN)"),
        MY_ACCOUNT_MINI_STATEMENT_END(USSDDataType.MY_ACCOUNT_MINI_STATEMENT_PIN.getValue() + "-MY_ACCOUNT_MINI_STATEMENT(END)"),

        //FULL STATEMENT
        MY_ACCOUNT_FULL_STATEMENT_MENU(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(MENU)"),//For type: FOSA / BOSA / ALL
        MY_ACCOUNT_FULL_STATEMENT_CUSTOMER(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_MENU.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(CUSTOMER)"),
        MY_ACCOUNT_FULL_STATEMENT_ACCOUNT(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_CUSTOMER.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(ACCOUNT)"),
        MY_ACCOUNT_FULL_STATEMENT_START_DATE(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_ACCOUNT.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(START_DATE)"),
        MY_ACCOUNT_FULL_STATEMENT_END_DATE(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_START_DATE.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(END_DATE)"),
        MY_ACCOUNT_FULL_STATEMENT_EMAIL_ADDRESS(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_END_DATE.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(EMAIL_ADDRESS)"),
        MY_ACCOUNT_FULL_STATEMENT_PIN(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_EMAIL_ADDRESS.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(PIN)"),
        MY_ACCOUNT_FULL_STATEMENT_CONFIRMATION(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_PIN.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(CONFIRMATION)"),
        MY_ACCOUNT_FULL_STATEMENT_END(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_CONFIRMATION.getValue() + "-MY_ACCOUNT_FULL_STATEMENT(END)"),

        //DIVIDEND PAYSLIP
        MY_ACCOUNT_DIVIDEND_PAYSLIP_MENU(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MY_ACCOUNT_DIVIDEND_PAYSLIP(MENU)"),//For type: FOSA / BOSA / ALL
        MY_ACCOUNT_DIVIDEND_PAYSLIP_YEAR(USSDDataType.MY_ACCOUNT_DIVIDEND_PAYSLIP_MENU.getValue() + "-MY_ACCOUNT_DIVIDEND_PAYSLIP(YEAR)"),
        MY_ACCOUNT_DIVIDEND_PAYSLIP_EMAIL_ADDRESS(USSDDataType.MY_ACCOUNT_DIVIDEND_PAYSLIP_YEAR.getValue() + "-MY_ACCOUNT_DIVIDEND_PAYSLIP(EMAIL_ADDRESS)"),
        MY_ACCOUNT_DIVIDEND_PAYSLIP_PIN(USSDDataType.MY_ACCOUNT_DIVIDEND_PAYSLIP_EMAIL_ADDRESS.getValue() + "-MY_ACCOUNT_DIVIDEND_PAYSLIP(PIN)"),
        MY_ACCOUNT_DIVIDEND_PAYSLIP_CONFIRMATION(USSDDataType.MY_ACCOUNT_FULL_STATEMENT_PIN.getValue() + "-MY_ACCOUNT_DIVIDEND_PAYSLIP(CONFIRMATION)"),
        MY_ACCOUNT_DIVIDEND_PAYSLIP_END(USSDDataType.MY_ACCOUNT_DIVIDEND_PAYSLIP_CONFIRMATION.getValue() + "-MY_ACCOUNT_DIVIDEND_PAYSLIP(END)"),

        //STANDING ORDER
        STANDING_ORDER_MENU(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-STANDING_ORDER(MENU)"),
        STANDING_ORDER_VIEW(USSDDataType.STANDING_ORDER_MENU.getValue() + "-STANDING_ORDER_VIEW(VIEW)"),
        STANDING_ORDER_END(USSDDataType.STANDING_ORDER_MENU.getValue() + "-STANDING_ORDER_VIEW(END)"),

        STANDING_ORDER_CREATION_CUSTOMER(USSDDataType.STANDING_ORDER_MENU.getValue() + "-STANDING_ORDER_CREATION(CUSTOMER)"),
        STANDING_ORDER_CREATION_SOURCE_ACCOUNT(USSDDataType.STANDING_ORDER_CREATION_CUSTOMER.getValue() + "-STANDING_ORDER_CREATION(SOURCE_ACCOUNT)"),
        STANDING_ORDER_CREATION_DESTINATION_OPTION(USSDDataType.STANDING_ORDER_CREATION_SOURCE_ACCOUNT.getValue() + "-STANDING_ORDER_CREATION(DESTINATION_OPTION)"),
        STANDING_ORDER_CREATION_DESTINATION_CUSTOMER(USSDDataType.STANDING_ORDER_CREATION_DESTINATION_OPTION.getValue() + "-STANDING_ORDER_CREATION(DESTINATION_CUSTOMER)"),
        STANDING_ORDER_CREATION_DESTINATION_ACCOUNT(USSDDataType.STANDING_ORDER_CREATION_DESTINATION_CUSTOMER.getValue() + "-STANDING_ORDER_CREATION(DESTINATION_ACCOUNT)"),
        STANDING_ORDER_CREATION_STO_NAME(USSDDataType.STANDING_ORDER_CREATION_DESTINATION_ACCOUNT.getValue() + "-STANDING_ORDER_CREATION(STO_NAME)"),
        STANDING_ORDER_CREATION_START_DATE(USSDDataType.STANDING_ORDER_CREATION_STO_NAME.getValue() + "-STANDING_ORDER_CREATION(START_DATE)"),
        STANDING_ORDER_CREATION_AMOUNT(USSDDataType.STANDING_ORDER_CREATION_START_DATE.getValue() + "-STANDING_ORDER_CREATION(AMOUNT)"),
        STANDING_ORDER_CREATION_PIN(USSDDataType.STANDING_ORDER_CREATION_AMOUNT.getValue() + "-STANDING_ORDER_CREATION(PIN)"),
        STANDING_ORDER_CREATION_CONFIRMATION(USSDDataType.STANDING_ORDER_CREATION_PIN.getValue() + "-STANDING_ORDER_CREATION(CONFIRMATION)"),
        STANDING_ORDER_CREATION_END(USSDDataType.STANDING_ORDER_CREATION_CONFIRMATION.getValue() + "-STANDING_ORDER_CREATION(END)"),

        ATM_CARD_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-ATM_CARD(ACTION)"),
        ATM_CARD_LIST(USSDDataType.ATM_CARD_ACTION.getValue() + "-ATM_CARD(LIST)"),
        ATM_CARD_PIN(USSDDataType.ATM_CARD_LIST.getValue() + "-ATM_CARD(PIN)"),
        ATM_CARD_CONFIRMATION(USSDDataType.ATM_CARD_PIN.getValue() + "-ATM_CARD(CONFIRMATION)"),
        ATM_CARD_END(USSDDataType.ATM_CARD_CONFIRMATION.getValue() + "-ATM_CARD(END)"),

        //MAPP_ACTIVATION
        MAPP_ACTIVATION_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MAPP_ACTIVATION(ACTION)"),
        MAPP_ACTIVATION_PIN(USSDDataType.MAPP_ACTIVATION_ACTION.getValue() + "-MAPP_ACTIVATION(PIN)"),
        MAPP_ACTIVATION_CONFIRMATION(USSDDataType.MAPP_ACTIVATION_PIN.getValue() + "-MAPP_ACTIVATION(CONFIRMATION)"),
        MAPP_ACTIVATION_END(USSDDataType.MAPP_ACTIVATION_CONFIRMATION.getValue() + "-MAPP_ACTIVATION(END)"),


        //WAPP_ACTIVATION
        WAPP_ACTIVATION_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-WAPP_ACTIVATION(ACTION)"),
        WAPP_ACTIVATION_CONFIRMATION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-WAPP_ACTIVATION(CONFIRMATION)"),
        WAPP_ACTIVATION_END(USSDDataType.WAPP_ACTIVATION_CONFIRMATION.getValue() + "-WAPP_ACTIVATION(END)"),


        //MEMBERS_PORTAL ACTIVATION
        MEMBERS_PORTAL_ACTIVATION_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MEMBERS_PORTAL_ACTIVATION(ACTION)"),
        MEMBERS_PORTAL_ACTIVATION_PIN(USSDDataType.MEMBERS_PORTAL_ACTIVATION_ACTION.getValue() + "-MEMBERS_PORTAL_ACTIVATION(PIN)"),
        MEMBERS_PORTAL_ACTIVATION_CONFIRMATION(USSDDataType.MEMBERS_PORTAL_ACTIVATION_PIN.getValue() + "-MEMBERS_PORTAL_ACTIVATION(CONFIRMATION)"),
        MEMBERS_PORTAL_ACTIVATION_END(USSDDataType.MEMBERS_PORTAL_ACTIVATION_CONFIRMATION.getValue() + "-MEMBERS_PORTAL_ACTIVATION(END)"),

        //MEMBERS_PORTAL Deactivation
        MEMBERS_PORTAL_DEACTIVATION_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MEMBERS_PORTAL_DEACTIVATION(ACTION)"),
        MEMBERS_PORTAL_DEACTIVATION_PIN(USSDDataType.MEMBERS_PORTAL_DEACTIVATION_ACTION.getValue() + "-MEMBERS_PORTAL_DEACTIVATION(PIN)"),
        MEMBERS_PORTAL_DEACTIVATION_CONFIRMATION(USSDDataType.MEMBERS_PORTAL_DEACTIVATION_PIN.getValue() + "-MEMBERS_PORTAL_DEACTIVATION(CONFIRMATION)"),
        MEMBERS_PORTAL_DEACTIVATION_END(USSDDataType.MEMBERS_PORTAL_DEACTIVATION_CONFIRMATION.getValue() + "-MEMBERS_PORTAL_DEACTIVATION(END)"),

        //Members Portal Password Reset
        MEMBERS_PORTAL_PASSWORD_RESET_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MEMBERS_PORTAL_PASSWORD_RESET(ACTION)"),
        MEMBERS_PORTAL_PASSWORD_RESET_PIN(USSDDataType.MEMBERS_PORTAL_PASSWORD_RESET_ACTION.getValue() + "-MEMBERS_PORTAL_PASSWORD_RESET(PIN)"),
        MEMBERS_PORTAL_PASSWORD_RESET_CONFIRMATION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MEMBERS_PORTAL_PASSWORD_RESET(CONFIRMATION)"),
        MEMBERS_PORTAL_PASSWORD_RESET_END(USSDDataType.MEMBERS_PORTAL_PASSWORD_RESET_CONFIRMATION.getValue() + "-MEMBERS_PORTAL_PASSWORD_RESET(END)"),

        //Members Portal enrollment
        MEMBERS_PORTAL_ENROLLMENT_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-MEMBERS_PORTAL_ENROLLMENT(ACTION)"),
        MEMBERS_PORTAL_ENROLLMENT_PIN(USSDDataType.MEMBERS_PORTAL_ENROLLMENT_ACTION.getValue() + "-MEMBERS_PORTAL_ENROLLMENT(PIN)"),
        MEMBERS_PORTAL_ENROLLMENT_CONFIRMATION(USSDDataType.MEMBERS_PORTAL_ENROLLMENT_PIN.getValue() + "-MEMBERS_PORTAL_ENROLLMENT(CONFIRMATION)"),
        MEMBERS_PORTAL_ENROLLMENT_END(USSDDataType.MEMBERS_PORTAL_ENROLLMENT_CONFIRMATION.getValue() + "-MEMBERS_PORTAL_ENROLLMENT(END)"),


        //MEMBER_REGISTRATION
        ACCOUNT_REGISTRATION_ACTION(USSDDataType.MY_ACCOUNT_MENU.getValue() + "-ACCOUNT_REGISTRATION(ACTION)"),
        ACCOUNT_REGISTRATION_NAME(USSDDataType.ACCOUNT_REGISTRATION_ACTION.getValue() + "-ACCOUNT_REGISTRATION(NAME)"),
        ACCOUNT_REGISTRATION_MOBILE_NUMBER(USSDDataType.ACCOUNT_REGISTRATION_NAME.getValue() + "-ACCOUNT_REGISTRATION(MOBILE_NUMBER)"),
        ACCOUNT_REGISTRATION_NATIONAL_ID_NUMBER(USSDDataType.ACCOUNT_REGISTRATION_MOBILE_NUMBER.getValue() + "-ACCOUNT_REGISTRATION(NATIONAL_ID_NUMBER)"),
        ACCOUNT_REGISTRATION_DATE_OF_BIRTH(USSDDataType.ACCOUNT_REGISTRATION_NATIONAL_ID_NUMBER.getValue() + "-ACCOUNT_REGISTRATION(DATE_OF_BIRTH)"),
        ACCOUNT_REGISTRATION_PIN(USSDDataType.ACCOUNT_REGISTRATION_DATE_OF_BIRTH.getValue() + "-ACCOUNT_REGISTRATION(PIN)"),
        ACCOUNT_REGISTRATION_CONFIRMATION(USSDDataType.ACCOUNT_REGISTRATION_PIN.getValue() + "-ACCOUNT_REGISTRATION(CONFIRMATION)"),
        ACCOUNT_REGISTRATION_END(USSDDataType.ACCOUNT_REGISTRATION_CONFIRMATION.getValue() + "-ACCOUNT_REGISTRATION(END)"),

        //SELF_REGISTRATION
        SELF_REGISTRATION_ACTION(USSDDataType.INIT.getValue() + "-SELF_REGISTRATION(ACTION)"),
        SELF_REGISTRATION_NAME(USSDDataType.SELF_REGISTRATION_ACTION.getValue() + "-SELF_REGISTRATION(NAME)"),
        SELF_REGISTRATION_NATIONAL_ID_NUMBER(USSDDataType.SELF_REGISTRATION_NAME.getValue() + "-SELF_REGISTRATION(NATIONAL_ID_NUMBER)"),
        SELF_REGISTRATION_DATE_OF_BIRTH(USSDDataType.SELF_REGISTRATION_NATIONAL_ID_NUMBER.getValue() + "-SELF_REGISTRATION(DATE_OF_BIRTH)"),
        SELF_REGISTRATION_CONFIRMATION(USSDDataType.SELF_REGISTRATION_DATE_OF_BIRTH.getValue() + "-SELF_REGISTRATION(CONFIRMATION)"),
        SELF_REGISTRATION_END(USSDDataType.SELF_REGISTRATION_CONFIRMATION.getValue() + "-SELF_REGISTRATION(END)"),

        //LOAN
        LOAN_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-LOAN(MENU)"),
        LOAN_QUALIFICATION_TYPE(USSDDataType.LOAN_MENU.getValue() + "-LOAN_QUALIFICATION(TYPE)"),
        //LOAN_QUALIFICATION_AMOUNT(USSDDataType.LOAN_QUALIFICATION_TYPE.getValue() + "-LOAN_QUALIFICATION(AMOUNT)"),
        LOAN_QUALIFICATION_END(USSDDataType.LOAN_QUALIFICATION_TYPE.getValue() + "-LOAN_QUALIFICATION(END)"),

        LOAN_GUARANTORSHIP_ABILITY_END(USSDDataType.LOAN_MENU.getValue() + "-LOAN_GUARANTORSHIP_ABILITY(END)"),

        LOAN_APPLICATION_TYPE(USSDDataType.LOAN_MENU.getValue() + "-LOAN_APPLICATION(TYPE)"),
        LOAN_APPLICATION_PURPOSE(USSDDataType.LOAN_APPLICATION_TYPE.getValue() + "-LOAN_APPLICATION(PURPOSE)"),
        LOAN_APPLICATION_AMOUNT(USSDDataType.LOAN_APPLICATION_TYPE.getValue() + "-LOAN_APPLICATION(AMOUNT)"),
        LOAN_APPLICATION_PIN(USSDDataType.LOAN_APPLICATION_AMOUNT.getValue() + "-LOAN_APPLICATION(PIN)"),
        LOAN_APPLICATION_CONFIRMATION(USSDDataType.LOAN_APPLICATION_PIN.getValue() + "-LOAN_APPLICATION(CONFIRMATION)"),
        LOAN_APPLICATION_END(USSDDataType.LOAN_APPLICATION_CONFIRMATION.getValue() + "-LOAN_APPLICATION(END)"),


        LOAN_BALANCE_CUSTOMER(USSDDataType.LOAN_MENU.getValue() + "-LOAN_BALANCE(CUSTOMER)"),//For type: FOSA / BOSA / ALL
        LOAN_BALANCE_ACCOUNT(USSDDataType.LOAN_BALANCE_CUSTOMER.getValue() + "-LOAN_BALANCE(ACCOUNT)"),//For type: FOSA / BOSA / ALL
        LOAN_BALANCE_PIN(USSDDataType.LOAN_MENU.getValue() + "-LOAN_BALANCE(PIN)"),
        LOAN_BALANCE_END(USSDDataType.LOAN_BALANCE_PIN.getValue() + "-LOAN_BALANCE(END)"),

        LOAN_MINI_STATEMENT_MENU(USSDDataType.LOAN_MENU.getValue() + "-LOAN_MINI_STATEMENT(MENU)"),
        LOAN_MINI_STATEMENT_CUSTOMER(USSDDataType.LOAN_MINI_STATEMENT_MENU.getValue() + "-LOAN_MINI_STATEMENT(CUSTOMER)"),
        LOAN_MINI_STATEMENT_ACCOUNT(USSDDataType.LOAN_MINI_STATEMENT_CUSTOMER.getValue() + "-LOAN_MINI_STATEMENT(ACCOUNT)"),
        LOAN_MINI_STATEMENT_PIN(USSDDataType.LOAN_MINI_STATEMENT_ACCOUNT.getValue() + "-LOAN_MINI_STATEMENT(PIN)"),
        LOAN_MINI_STATEMENT_END(USSDDataType.LOAN_MINI_STATEMENT_PIN.getValue() + "-LOAN_MINI_STATEMENT(END)"),

        LOAN_REPAYMENT_OPTION(USSDDataType.LOAN_MENU.getValue() + "-LOAN_REPAYMENT(OPTION)"),
        LOAN_REPAYMENT_FUNDS_CUSTOMER(USSDDataType.LOAN_REPAYMENT_OPTION.getValue() + "-LOAN_REPAYMENT(FUNDS_CUSTOMER)"),
        LOAN_REPAYMENT_FUNDS_ACCOUNT(USSDDataType.LOAN_REPAYMENT_FUNDS_CUSTOMER.getValue() + "-LOAN_REPAYMENT(FUNDS_ACCOUNT)"),
        LOAN_REPAYMENT_CUSTOMER(USSDDataType.LOAN_REPAYMENT_FUNDS_ACCOUNT.getValue() + "-LOAN_REPAYMENT(CUSTOMER)"),
        LOAN_REPAYMENT_LOAN(USSDDataType.LOAN_REPAYMENT_CUSTOMER.getValue() + "-LOAN_REPAYMENT(LOAN)"),
        //LOAN_REPAYMENT_CLEARING(USSDDataType.LOAN_REPAYMENT_LOAN.getValue() + "-LOAN_REPAYMENT(CLEARING)"),
        LOAN_REPAYMENT_AMOUNT(USSDDataType.LOAN_REPAYMENT_LOAN.getValue() + "-LOAN_REPAYMENT(AMOUNT)"),
        LOAN_REPAYMENT_PIN(USSDDataType.LOAN_REPAYMENT_AMOUNT.getValue() + "-LOAN_REPAYMENT(PIN)"),
        LOAN_REPAYMENT_CONFIRMATION(USSDDataType.LOAN_REPAYMENT_PIN.getValue() + "-LOAN_REPAYMENT(CONFIRMATION)"),
        //LOAN_REPAYMENT_CLEARING_CONFIRMATION(USSDDataType.LOAN_REPAYMENT_PIN.getValue() + "-LOAN_REPAYMENT(CLEARING_CONFIRMATION)"),
        LOAN_REPAYMENT_END(USSDDataType.LOAN_REPAYMENT_CONFIRMATION.getValue() + "-LOAN_REPAYMENT(END)"),

        LOAN_GUARANTORS_TYPE(USSDDataType.LOAN_MENU.getValue() + "-LOAN_GUARANTORS(TYPE)"),
        LOAN_GUARANTORS_OPTION(USSDDataType.LOAN_GUARANTORS_TYPE.getValue() + "-LOAN_GUARANTORS(OPTION)"),
        LOAN_GUARANTORS_GUARANTORS(USSDDataType.LOAN_GUARANTORS_OPTION.getValue() + "-LOAN_GUARANTORS(GUARANTORS)"),
        LOAN_GUARANTORS_MOBILE_NUMBER(USSDDataType.LOAN_GUARANTORS_OPTION.getValue() + "-LOAN_GUARANTORS(MOBILE_NUMBER)"),
        LOAN_GUARANTORS_PIN(USSDDataType.LOAN_GUARANTORS_MOBILE_NUMBER.getValue() + "-LOAN_GUARANTORS(PIN)"),
        LOAN_GUARANTORS_CONFIRMATION(USSDDataType.LOAN_GUARANTORS_PIN.getValue() + "-LOAN_GUARANTORS(CONFIRMATION)"),
        LOAN_GUARANTORS_END(USSDDataType.LOAN_GUARANTORS_CONFIRMATION.getValue() + "-LOAN_GUARANTORS(END)"),


        LOANS_GUARANTEED_OPTION(USSDDataType.LOAN_MENU.getValue() + "-LOANS_GUARANTEED(OPTION)"),
        LOANS_GUARANTEED_TYPE(USSDDataType.LOANS_GUARANTEED_OPTION.getValue() + "-LOANS_GUARANTEED(TYPE)"),
        LOANS_GUARANTEED_LOAN_DETAILS(USSDDataType.LOANS_GUARANTEED_TYPE.getValue() + "-LOANS_GUARANTEED(LOAN_DETAILS)"),
        LOANS_GUARANTEED_PIN(USSDDataType.LOANS_GUARANTEED_LOAN_DETAILS.getValue() + "-LOANS_GUARANTEED(PIN)"),
        LOANS_GUARANTEED_CONFIRMATION(USSDDataType.LOANS_GUARANTEED_PIN.getValue() + "-LOANS_GUARANTEED(CONFIRMATION)"),
        LOANS_GUARANTEED_END(USSDDataType.LOANS_GUARANTEED_CONFIRMATION.getValue() + "-LOANS_GUARANTEED(END)"),

						/*LOAN_QUALIFICATION_TYPE(USSDDataType.LOAN_MENU.getValue() + "-LOAN_QUALIFICATION(TYPE)"),
							LOAN_QUALIFICATION_END(USSDDataType.LOAN_QUALIFICATION_TYPE.getValue() + "-LOAN_QUALIFICATION(END)"),

						LOAN_APPLICATION_TYPE(USSDDataType.LOAN_MENU.getValue() + "-LOAN_APPLICATION(TYPE)"),
							LOAN_APPLICATION_AMOUNT(USSDDataType.LOAN_APPLICATION_TYPE.getValue() + "-LOAN_APPLICATION(AMOUNT)"),
								LOAN_APPLICATION_PIN(USSDDataType.LOAN_APPLICATION_AMOUNT.getValue() + "-LOAN_APPLICATION(PIN)"),
									LOAN_APPLICATION_CONFIRMATION(USSDDataType.LOAN_APPLICATION_PIN.getValue() + "-LOAN_APPLICATION(CONFIRMATION)"),
										LOAN_APPLICATION_END(USSDDataType.LOAN_APPLICATION_CONFIRMATION.getValue() + "-LOAN_APPLICATION(END)"),


						LOAN_REPAYMENT_MENU(USSDDataType.LOAN_MENU.getValue() + "-LOAN_REPAYMENT(MENU)"),
							LOAN_REPAYMENT_ACCOUNT(USSDDataType.LOAN_REPAYMENT_MENU.getValue() + "-LOAN_REPAYMENT(ACCOUNT)"),
								LOAN_REPAYMENT_AMOUNT(USSDDataType.LOAN_REPAYMENT_ACCOUNT.getValue() + "-LOAN_REPAYMENT(AMOUNT)"),
									LOAN_REPAYMENT_PIN(USSDDataType.LOAN_REPAYMENT_AMOUNT.getValue() + "-LOAN_REPAYMENT(PIN)"),
											LOAN_REPAYMENT_CONFIRMATION(USSDDataType.LOAN_REPAYMENT_PIN.getValue() + "-LOAN_REPAYMENT(CONFIRMATION)"),
												LOAN_REPAYMENT_END(USSDDataType.LOAN_REPAYMENT_CONFIRMATION.getValue() + "-LOAN_REPAYMENT(END)"),
							*/

        //FUNDS TRANSFER
        FUNDS_TRANSFER_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-FUNDS_TRANSFER(MENU)"),

        //INTERNAL TRANSFER
        FUNDS_TRANSFER_INTERNAL_CUSTOMER(USSDDataType.FUNDS_TRANSFER_MENU.getValue() + "-FUNDS_TRANSFER_INTERNAL(CUSTOMER)"),
        FUNDS_TRANSFER_INTERNAL_FROM_ACCOUNT(USSDDataType.FUNDS_TRANSFER_INTERNAL_CUSTOMER.getValue() + "-FUNDS_TRANSFER_INTERNAL(FROM_ACCOUNT)"),
        FUNDS_TRANSFER_INTERNAL_OPTION(USSDDataType.FUNDS_TRANSFER_INTERNAL_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_INTERNAL(OPTION)"),
        FUNDS_TRANSFER_INTERNAL_TO_OPTION(USSDDataType.FUNDS_TRANSFER_INTERNAL_OPTION.getValue() + "-FUNDS_TRANSFER_INTERNAL(TO_OPTION)"),
        FUNDS_TRANSFER_INTERNAL_TO_IDENTIFIER(USSDDataType.FUNDS_TRANSFER_INTERNAL_TO_OPTION.getValue() + "-FUNDS_TRANSFER_INTERNAL(TO_IDENTIFIER)"),
        FUNDS_TRANSFER_INTERNAL_TO_ACCOUNT_CATEGORIES(USSDDataType.FUNDS_TRANSFER_INTERNAL_TO_IDENTIFIER.getValue() + "-FUNDS_TRANSFER_INTERNAL(TO_ACCOUNT_CATEGORIES)"),
        FUNDS_TRANSFER_INTERNAL_TO_ACCOUNT(USSDDataType.FUNDS_TRANSFER_INTERNAL_TO_ACCOUNT_CATEGORIES.getValue() + "-FUNDS_TRANSFER_INTERNAL(TO_ACCOUNT)"),
        FUNDS_TRANSFER_INTERNAL_OTHER_ACCOUNT(USSDDataType.FUNDS_TRANSFER_INTERNAL_TO_OPTION.getValue() + "-FUNDS_TRANSFER_INTERNAL(OTHER_ACCOUNT)"),
        FUNDS_TRANSFER_INTERNAL_AMOUNT(USSDDataType.FUNDS_TRANSFER_INTERNAL_TO_ACCOUNT.getValue() + "-FUNDS_TRANSFER_INTERNAL(AMOUNT)"),
        FUNDS_TRANSFER_INTERNAL_PIN(USSDDataType.FUNDS_TRANSFER_INTERNAL_AMOUNT.getValue() + "-FUNDS_TRANSFER_INTERNAL(PIN)"),
        FUNDS_TRANSFER_INTERNAL_CONFIRMATION(USSDDataType.FUNDS_TRANSFER_INTERNAL_PIN.getValue() + "-FUNDS_TRANSFER_INTERNAL(CONFIRMATION)"),
        FUNDS_TRANSFER_INTERNAL_END(USSDDataType.FUNDS_TRANSFER_INTERNAL_CONFIRMATION.getValue() + "-FUNDS_TRANSFER_INTERNAL(END)"),



        FUNDS_TRANSFER_EXTERNAL_TRANSFER_OPTION(USSDDataType.FUNDS_TRANSFER_MENU.getValue() + "-FUNDS_TRANSFER_EXTERNAL(TRANSFER_OPTION)"),
        FUNDS_TRANSFER_EXTERNAL_CUSTOMER(USSDDataType.FUNDS_TRANSFER_EXTERNAL_TRANSFER_OPTION.getValue() + "-FUNDS_TRANSFER_EXTERNAL(CUSTOMER)"),
        //EXTERNAL TRANSFER
        FUNDS_TRANSFER_EXTERNAL_BANK(USSDDataType.FUNDS_TRANSFER_EXTERNAL_TRANSFER_OPTION.getValue() + "-FUNDS_TRANSFER_EXTERNAL(BANK)"),
        FUNDS_TRANSFER_EXTERNAL_TO_BANK_ACCOUNT_NO(USSDDataType.FUNDS_TRANSFER_EXTERNAL_BANK.getValue() + "-FUNDS_TRANSFER_EXTERNAL(TO_BANK_ACCOUNT_NO)"),
        FUNDS_TRANSFER_EXTERNAL_TO_BANK_ACCOUNT_NAME(USSDDataType.FUNDS_TRANSFER_EXTERNAL_TO_BANK_ACCOUNT_NO.getValue() + "-FUNDS_TRANSFER_EXTERNAL(TO_BANK_ACCOUNT_NO)"),
        FUNDS_TRANSFER_EXTERNAL_FROM_ACCOUNT(USSDDataType.FUNDS_TRANSFER_EXTERNAL_TO_BANK_ACCOUNT_NAME.getValue() + "-FUNDS_TRANSFER_EXTERNAL(FROM_ACCOUNT)"),
        FUNDS_TRANSFER_EXTERNAL_AMOUNT(USSDDataType.FUNDS_TRANSFER_EXTERNAL_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_EXTERNAL(AMOUNT)"),
        FUNDS_TRANSFER_EXTERNAL_PIN(USSDDataType.FUNDS_TRANSFER_EXTERNAL_AMOUNT.getValue() + "-FUNDS_TRANSFER_EXTERNAL(PIN)"),
        FUNDS_TRANSFER_EXTERNAL_CONFIRMATION(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PIN.getValue() + "-FUNDS_TRANSFER_EXTERNAL(CONFIRMATION)"),
        FUNDS_TRANSFER_EXTERNAL_END(USSDDataType.FUNDS_TRANSFER_EXTERNAL_CONFIRMATION.getValue() + "-FUNDS_TRANSFER_EXTERNAL(END)"),

        FUNDS_TRANSFER_PESALINK_OPTION(USSDDataType.FUNDS_TRANSFER_MENU.getValue() + "-FUNDS_TRANSFER_PESALINK(TRANSFER_OPTION)"),

        //PESALINK TRANSFER EXTERNAL
        FUNDS_TRANSFER_EXTERNAL_PESALINK_OPTION(USSDDataType.FUNDS_TRANSFER_EXTERNAL_BANK.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(OPTION)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_CUSTOMER(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_OPTION.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(CUSTOMER)"),

        //PESALINK TRANSFER
        FUNDS_TRANSFER_EXTERNAL_PESALINK_BANK(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_CUSTOMER.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(BANK)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_TO_BANK_ACCOUNT_NO(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_BANK.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(TO_BANK_ACCOUNT_NO)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_TO_BANK_ACCOUNT_NAME(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_TO_BANK_ACCOUNT_NO.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(TO_BANK_ACCOUNT_NO)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_FROM_ACCOUNT(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_TO_BANK_ACCOUNT_NAME.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(FROM_ACCOUNT)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_AMOUNT(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(AMOUNT)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_PIN(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_AMOUNT.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(PIN)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_CONFIRMATION(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_PIN.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(CONFIRMATION)"),
        FUNDS_TRANSFER_EXTERNAL_PESALINK_END(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_CONFIRMATION.getValue() + "-FUNDS_TRANSFER_EXTERNAL_PESALINK(END)"),



        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_CUSTOMER(USSDDataType.FUNDS_TRANSFER_EXTERNAL_PESALINK_OPTION.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(CUSTOMER)"),
        //PESALINK TRANSFER
        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_FROM_ACCOUNT(USSDDataType.FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_CUSTOMER.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(FROM_ACCOUNT)"),
        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_TO_ACCOUNT(USSDDataType.FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_CUSTOMER.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(TO_BANK_ACCOUNT_NO)"),
        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_MOBILE(USSDDataType.FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(MOBILE)"),
        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_AMOUNT(USSDDataType.FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_MOBILE.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(AMOUNT)"),
        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_PIN(USSDDataType.FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_AMOUNT.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(PIN)"),
        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_CONFIRMATION(USSDDataType.FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_PIN.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(CONFIRMATION)"),
        FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_END(USSDDataType.FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER_CONFIRMATION.getValue() + "-FUNDS_TRANSFER_PESALINK_MOBILE_TRANSFER(END)"),

        //FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT
        FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT_MENU(USSDDataType.FUNDS_TRANSFER_EXTERNAL_BANK.getValue() + "-FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT(MENU)"),
        FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT_ACCOUNT(USSDDataType.FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT_MENU.getValue() + "-FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT(ACCOUNT)"),
        FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT_NAME(USSDDataType.FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT_ACCOUNT.getValue() + "-FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT(NAME)"),
        FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT_REMOVE(USSDDataType.FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT_MENU.getValue() + "-FUNDS_TRANSFER_EXTERNAL_MAINTENANCE_ACCOUNT(REMOVE)"),

        FUNDS_TRANSFER_PAYBILL_CUSTOMER(USSDDataType.FUNDS_TRANSFER_MENU.getValue() + "-FUNDS_TRANSFER_PAYBILL(CUSTOMER)"),
        FUNDS_TRANSFER_PAYBILL_FROM_ACCOUNT(USSDDataType.FUNDS_TRANSFER_PAYBILL_CUSTOMER.getValue() + "-FUNDS_TRANSFER_PAYBILL(FROM_ACCOUNT)"),
        FUNDS_TRANSFER_PAYBILL_CODE(USSDDataType.FUNDS_TRANSFER_PAYBILL_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_PAYBILL(PAYBILL_CODE)"),
        FUNDS_TRANSFER_PAYBILL_ACCOUNT_NUMBER(USSDDataType.FUNDS_TRANSFER_PAYBILL_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_PAYBILL(PAYBILL_ACCOUNT_NUMBER)"),
        FUNDS_TRANSFER_PAYBILL_AMOUNT(USSDDataType.FUNDS_TRANSFER_PAYBILL_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_PAYBILL(AMOUNT)"),
        FUNDS_TRANSFER_PAYBILL_PIN(USSDDataType.FUNDS_TRANSFER_PAYBILL_AMOUNT.getValue() + "-FUNDS_TRANSFER_PAYBILL(PIN)"),
        FUNDS_TRANSFER_PAYBILL_CONFIRMATION(USSDDataType.FUNDS_TRANSFER_PAYBILL_PIN.getValue() + "-FUNDS_TRANSFER_PAYBILL(CONFIRMATION)"),
        FUNDS_TRANSFER_PAYBILL_END(USSDDataType.FUNDS_TRANSFER_PAYBILL_CONFIRMATION.getValue() + "-FUNDS_TRANSFER_PAYBILL(END)"),


        FUNDS_TRANSFER_TILL_CUSTOMER(USSDDataType.FUNDS_TRANSFER_MENU.getValue() + "-FUNDS_TRANSFER_TILL(CUSTOMER)"),
        FUNDS_TRANSFER_TILL_FROM_ACCOUNT(USSDDataType.FUNDS_TRANSFER_TILL_CUSTOMER.getValue() + "-FUNDS_TRANSFER_TILL(FROM_ACCOUNT)"),
        FUNDS_TRANSFER_TILL_CODE(USSDDataType.FUNDS_TRANSFER_TILL_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_TILL(TILL_CODE)"),
        FUNDS_TRANSFER_TILL_AMOUNT(USSDDataType.FUNDS_TRANSFER_TILL_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_TILL(AMOUNT)"),
        FUNDS_TRANSFER_TILL_PIN(USSDDataType.FUNDS_TRANSFER_TILL_AMOUNT.getValue() + "-FUNDS_TRANSFER_TILL(PIN)"),
        FUNDS_TRANSFER_TILL_CONFIRMATION(USSDDataType.FUNDS_TRANSFER_TILL_PIN.getValue() + "-FUNDS_TRANSFER_TILL(CONFIRMATION)"),
        FUNDS_TRANSFER_TILL_END(USSDDataType.FUNDS_TRANSFER_TILL_CONFIRMATION.getValue() + "-FUNDS_TRANSFER_TILL(END)"),

        FUNDS_TRANSFER_LIPA_NA_CUSTOMER(USSDDataType.FUNDS_TRANSFER_MENU.getValue() + "-FUNDS_TRANSFER_LIPA_NA(CUSTOMER)"),
        FUNDS_TRANSFER_LIPA_NA_FROM_ACCOUNT(USSDDataType.FUNDS_TRANSFER_LIPA_NA_CUSTOMER.getValue() + "-FUNDS_TRANSFER_LIPA_NA(FROM_ACCOUNT)"),
        FUNDS_TRANSFER_LIPA_NA_CODE(USSDDataType.FUNDS_TRANSFER_LIPA_NA_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_LIPA_NA(LIPA_NA_CODE)"),
        FUNDS_TRANSFER_LIPA_NA_AMOUNT(USSDDataType.FUNDS_TRANSFER_LIPA_NA_FROM_ACCOUNT.getValue() + "-FUNDS_TRANSFER_LIPA_NA(AMOUNT)"),
        FUNDS_TRANSFER_LIPA_NA_PIN(USSDDataType.FUNDS_TRANSFER_LIPA_NA_AMOUNT.getValue() + "-FUNDS_TRANSFER_LIPA_NA(PIN)"),
        FUNDS_TRANSFER_LIPA_NA_CONFIRMATION(USSDDataType.FUNDS_TRANSFER_LIPA_NA_PIN.getValue() + "-FUNDS_TRANSFER_LIPA_NA(CONFIRMATION)"),
        FUNDS_TRANSFER_LIPA_NA_END(USSDDataType.FUNDS_TRANSFER_LIPA_NA_CONFIRMATION.getValue() + "-FUNDS_TRANSFER_LIPA_NA(END)"),

        //WAPP_ACTIVATION
        ACTION_PRODUCT_PURCHASE_REQUEST(USSDDataType.MAIN_IN_MENU.getValue() + "-ACTION_PRODUCT_PURCHASE_REQUEST(PURCHASE_REQUEST)"),
        ACTION_PRODUCT_PURCHASE_REQUEST_ACTION(USSDDataType.ACTION_PRODUCT_PURCHASE_REQUEST.getValue() + "-ACTION_PRODUCT_PURCHASE_REQUEST(ACTION)"),
        ACTION_PRODUCT_PURCHASE_REQUEST_CONFIRMATION(USSDDataType.ACTION_PRODUCT_PURCHASE_REQUEST_ACTION.getValue() + "-ACTION_PRODUCT_PURCHASE_REQUEST(CONFIRMATION)"),
        ACTION_PRODUCT_PURCHASE_REQUEST_END(USSDDataType.ACTION_PRODUCT_PURCHASE_REQUEST_CONFIRMATION.getValue() + "-ACTION_PRODUCT_PURCHASE_REQUEST(END)"),


        //ACCOUNT_REGISTRATION_MENU
        //ACCOUNT_REGISTRATION_MENU(USSDDataType.MAIN_IN_MENU.getValue() + "-ACCOUNT_REGISTRATION(MENU)"),
        //BINGWA SACCO TO PROVIDE CLARITY ON SUB MENUS

        //CHANGE_PIN
        CHANGE_PIN_CURRENT_PIN(USSDDataType.MAIN_IN_MENU.getValue() + "-CHANGE_PIN(CURRENT_PIN)"),
        CHANGE_PIN_NEW_PIN(USSDDataType.CHANGE_PIN_CURRENT_PIN.getValue() + "-CHANGE_PIN(NEW_PIN)"),
        CHANGE_PIN_CONFIRM_PIN(USSDDataType.CHANGE_PIN_NEW_PIN.getValue() + "-CHANGE_PIN(CONFIRM_PIN)"),
        CHANGE_PIN_END(USSDDataType.CHANGE_PIN_CONFIRM_PIN.getValue() + "-CHANGE_PIN(END)"),


        //FORGOT PIN
        FORGOT_PIN_ID_NO(USSDDataType.INIT.getValue() + "-FORGOT_PIN(ID_NO)"),
        FORGOT_PIN_DOB(USSDDataType.FORGOT_PIN_ID_NO.getValue() + "-FORGOT_PIN(DOB)"),
        FORGOT_PIN_END(USSDDataType.FORGOT_PIN_DOB.getValue() + "-FORGOT_PIN(END)"),

        TERMS_AND_CONDITIONS(USSDDataType.LOGIN_PIN.getValue() + "-TERMS_AND_CONDITIONS(TC)"),
        TERMS_AND_CONDITIONS_END(USSDDataType.TERMS_AND_CONDITIONS.getValue() + "-TERMS_AND_CONDITIONS(END)"),

        //SET_PIN
        SET_PIN_ID_NO(USSDDataType.LOGIN_PIN.getValue() + "-SET_PIN(ID_NO)"),
        SET_PIN_NEW_PIN(USSDDataType.SET_PIN_ID_NO.getValue() + "-SET_PIN(NEW_PIN)"),
        SET_PIN_CONFIRM_PIN(USSDDataType.SET_PIN_NEW_PIN.getValue() + "-SET_PIN(CONFIRM_PIN)"),
        SET_PIN_END(USSDDataType.SET_PIN_CONFIRM_PIN.getValue() + "-SET_PIN(END)"),

        //GENERAL_MENU
        GENERAL_MENU(USSDDataType.INIT.getValue() + "-GENERAL(MENU)"),

        //BUSINESS_SHORT_CODE
        BUY_GOODS_MENU(USSDDataType.GENERAL_MENU.getValue() + "-BUY_GOODS(BUY_GOODS)"),
        BUY_GOODS_BUSINESS_SHORT_CODE(USSDDataType.BUY_GOODS_MENU.getValue() + "-BUY_GOODS(BUSINESS_SHORT_CODE)"),
        BUY_GOODS_AMOUNT(USSDDataType.BUY_GOODS_BUSINESS_SHORT_CODE.getValue() + "-BUY_GOODS(AMOUNT)"),
        BUY_GOODS_CONFIRMATION(USSDDataType.BUY_GOODS_AMOUNT.getValue() + "-BUY_GOODS(CONFIRMATION)"),
        BUY_GOODS_END(USSDDataType.BUY_GOODS_CONFIRMATION.getValue() + "-BUY_GOODS(END)"),

        USSD_PROCESS_OVERIDE_BACK("USSD_PROCESS_OVERIDE(BACK)"),
        USSD_PROCESS_OVERIDE_HOME("USSD_PROCESS_OVERIDE(HOME)"),
        USSD_PROCESS_OVERIDE_ERROR("USSD_PROCESS_OVERIDE(ERROR)"),
        USSD_PROCESS_OVERIDE_DATA_TYPE_NOT_FOUND("USSD_PROCESS_OVERIDE(DATA_TYPE_NOT_FOUND)");

        private final String strValue;

        USSDDataType(String theValue) {
            this.strValue = theValue;
        }

        public String getValue() {
            return strValue;
        }
    }

    public enum MobileMandates {
        BALANCE_ENQUIRY("BALANCE_ENQUIRY"),
        ACCOUNT_STATEMENT("ACCOUNT_STATEMENT"),
        DEPOSIT("DEPOSIT"),
        WITHDRAWAL("WITHDRAWAL"),
        INTERNAL_TRANSFER("INTERNAL_TRANSFER"),
        BANK_TRANSFER("BANK_TRANSFER"),
        UTILITY_PAYMENTS("UTILITY_PAYMENTS"),
        BUY_AIRTIME("BUY_AIRTIME"),
        LOAN_QUALIFICATION("LOAN_QUALIFICATION"),
        LOAN_APPLICATION("LOAN_APPLICATION"),
        LOAN_REPAYMENT("LOAN_REPAYMENT"),
        LOAN_STATEMENT("LOAN_STATEMENT"),
        LOAN_BALANCE("LOAN_BALANCE"),
        LOAN_GUARANTORSHIP("LOAN_GUARANTORSHIP"),
        MEMBER_ONBOARDING("MEMBER_ONBOARDING");

        private final String strValue;

        MobileMandates(String theValue) {
            this.strValue = theValue;
        }

        public String getValue() {
            return strValue;
        }

    }

    public enum ChargeServices {

        MPESA_WITHDRAWAL("MPESA_WITHDRAWAL"),
        AIRTIME_PURCHASE("AIRTIME_PURCHASE"),
        BILL_PAYMENT("BILL_PAYMENT"),
        BANK_TRANSFER("BANK_TRANSFER"),
        IFT_ACCOUNT_TO_ACCOUNT("IFT_ACCOUNT_TO_ACCOUNT"),
        DEPOSIT("DEPOSIT"),
        SINGLE_ACCOUNT_BALANCE_ENQUIRY("SINGLE_ACCOUNT_BALANCE_ENQUIRY"),
        ACCOUNT_MINI_STATEMENT("ACCOUNT_MINI_STATEMENT"),
        ACCOUNT_FULL_STATEMENT("ACCOUNT_FULL_STATEMENT"),
        LOAN_BALANCE_ENQUIRY("LOAN_BALANCE_ENQUIRY"),
        LOAN_MINI_STATEMENT("LOAN_MINI_STATEMENT"),
        LOAN_FULL_STATEMENT("LOAN_FULL_STATEMENT"),
        LOAN_APPLICATION("LOAN_APPLICATION"),
        IFT_LOAN_REPAYMENT("IFT_LOAN_REPAYMENT"),
        CHECK_LOAN_LIMIT("CHECK_LOAN_LIMIT"),
        GUARANTORSHIP_ABILITY_ENQUIRY("GUARANTORSHIP_ABILITY_ENQUIRY");

        private final String strValue;

        ChargeServices(String theValue) {
            this.strValue = theValue;
        }

        public String getValue() {
            return strValue;
        }

    }

    public enum MobileBankingServices {
        BALANCE_ENQUIRY("BALANCE_ENQUIRY"),
        ACCOUNT_STATEMENT("ACCOUNT_STATEMENT"),
        DEPOSIT_VIA_MPESA("DEPOSIT_VIA_MPESA"),
        WITHDRAWAL_VIA_MPESA("WITHDRAWAL_VIA_MPESA"),
        BANK_TRANSFER("BANK_TRANSFER"),
        UTILITY_PAYMENTS("UTILITY_PAYMENTS"),
        BUY_AIRTIME("BUY_AIRTIME"),
        INTERNAL_FUNDS_TRANSFER("INTERNAL_FUNDS_TRANSFER"),
        LOAN_QUALIFICATION("LOAN_QUALIFICATION"),
        LOAN_APPLICATION("LOAN_APPLICATION"),
        LOAN_REPAYMENT("LOAN_REPAYMENT"),
        LOAN_STATEMENT("LOAN_STATEMENT"),
        LOAN_BALANCE("LOAN_BALANCE");

        private final String strValue;

        MobileBankingServices(String theValue) {
            this.strValue = theValue;
        }

        public String getValue() {
            return strValue;
        }

    }

    public enum MobileBankingChannel {
        USSD("USSD"),
        MAPP("MAPP");

        private final String strValue;

        MobileBankingChannel(String theValue) {
            this.strValue = theValue;
        }

        public String getValue() {
            return strValue;
        }

    }


}
