manager.query.connection.logs.display=false
manager.query.connection.logs.files=/bin/service-wrapper/logs/connections.log

cbs.request.logs.display=true
cbs.response.logs.display=true
dynamics.cbs.request.logs.display=true
dynamics.cbs.response.logs.display=true

dynamics.cbs.callservice.request.logs.display=false
dynamics.cbs.callservice.response.logs.display=false

